filebeat.prospectors:
- input_type: log
  paths:
    - /mnt/log/*.log

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  username: elastic
  password: changeme
  template.path: /usr/share/filebeat/filebeat.template.json
  template.versions.2x.path: /usr/share/filebeat/filebeat.template-es2x.json
  template.versions.6x.path: /usr/share/filebeat/filebeat.template-es6x.json
